sudo: false
language: python
python:
  - "3.6"
os:
  - linux
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-runner
  - pip install codecov
script:
  - python setup.py test
after_success:
  - codecov
